-- Generated by apps/pokedex-web/scripts/generate.ts from PokéAPI. Do not edit;
-- change the script and run it again.
--
-- Data from PokéAPI, © 2013–2023 Paul Hallett and PokéAPI contributors, BSD 3-Clause.
-- The licence is in LICENSES/PokeAPI-BSD-3-Clause.txt.
--
-- With the earlier generated migrations, it says every form up to national
-- No.1025 that its games had, 1485 of them, and their entries in the
-- national, kanto, johto, hoenn, sinnoh, unova, kalos, alola, galar, hisui, paldea, lumiose pokedexes. Only the rows that differ from what
-- those wrote are here, and the forms they wrote that are no longer in.

insert into public.pokedex_species (id, slug, ko_name, en_name, ko_form_name, en_form_name, form_of, ko_genus, en_genus, generation, category, type1, type2, hp, attack, defense, special_attack, special_defense, speed, height, weight, growth_rate, capture_rate, hatch_counter, gender_rate, evolves_from_id, evolution_method, sprites) values
  (855, 'polteageist-phony', '포트데스', 'Polteageist', '위작폼', 'Phony Form', null, '홍차포켓몬', 'Black Tea Pokémon', 8, null,
   'ghost', null, 60, 65, 65, 134, 114, 70, 2, 4,
   'medium', 60, 20, -1,
   854, 'use-item-cracked-pot', '{"front":"/sprites/pokemon/855.png","front_shiny":"/sprites/pokemon/shiny/855.png","artwork":"/sprites/pokemon/artwork/855.png","artwork_shiny":"/sprites/pokemon/artwork/shiny/855.png"}'),
  (10345, 'polteageist-antique', '포트데스', 'Polteageist', '진작폼', 'Antique Form', 855, '홍차포켓몬', 'Black Tea Pokémon', 8, null,
   'ghost', null, 60, 65, 65, 134, 114, 70, 2, 4,
   'medium', 60, 20, -1,
   null, null, '{"front":"/sprites/pokemon/10345.png","front_shiny":"/sprites/pokemon/shiny/10345.png","artwork":"/sprites/pokemon/artwork/10345.png","artwork_shiny":"/sprites/pokemon/artwork/shiny/10345.png"}'),
  (1013, 'sinistcha-unremarkable', '그우린차', 'Sinistcha', '범작의 모습', 'Unremarkable Form', null, '말차포켓몬', 'Matcha Pokémon', 9, null,
   'grass', 'ghost', 71, 60, 106, 121, 80, 70, 2, 22,
   'slow', 60, 50, -1,
   1012, 'use-item-unremarkable-teacup', '{"front":"/sprites/pokemon/1013.png","front_shiny":"/sprites/pokemon/shiny/1013.png","artwork":"/sprites/pokemon/artwork/1013.png","artwork_shiny":"/sprites/pokemon/artwork/shiny/1013.png"}'),
  (10448, 'sinistcha-masterpiece', '그우린차', 'Sinistcha', '걸작의 모습', 'Masterpiece Form', 1013, '말차포켓몬', 'Matcha Pokémon', 9, null,
   'grass', 'ghost', 71, 60, 106, 121, 80, 70, 2, 22,
   'slow', 60, 50, -1,
   null, null, '{"front":"/sprites/pokemon/10448.png","front_shiny":"/sprites/pokemon/shiny/10448.png","artwork":"/sprites/pokemon/artwork/10448.png","artwork_shiny":"/sprites/pokemon/artwork/shiny/10448.png"}')
on conflict (id) do update set
  slug = excluded.slug,
  ko_name = excluded.ko_name,
  en_name = excluded.en_name,
  ko_form_name = excluded.ko_form_name,
  en_form_name = excluded.en_form_name,
  form_of = excluded.form_of,
  ko_genus = excluded.ko_genus,
  en_genus = excluded.en_genus,
  generation = excluded.generation,
  category = excluded.category,
  type1 = excluded.type1,
  type2 = excluded.type2,
  hp = excluded.hp,
  attack = excluded.attack,
  defense = excluded.defense,
  special_attack = excluded.special_attack,
  special_defense = excluded.special_defense,
  speed = excluded.speed,
  height = excluded.height,
  weight = excluded.weight,
  growth_rate = excluded.growth_rate,
  capture_rate = excluded.capture_rate,
  hatch_counter = excluded.hatch_counter,
  gender_rate = excluded.gender_rate,
  evolves_from_id = excluded.evolves_from_id,
  evolution_method = excluded.evolution_method,
  sprites = excluded.sprites;

insert into public.pokedex_entries (dex, number, species_id, is_default, ko_description, en_description) values
  ('national', 855, 10345, false, '남겨진 홍차를 발견하면 자신의 몸을 흘러 들어가게 한다. 그 홍차는 포트데스가 된다.', 'Leaving leftover black tea unattended is asking for this Pokémon to come along and pour itself into it, turning the tea into a new Polteageist.'),
  ('national', 1013, 10448, false, null, 'It prefers cool, dark places, such as the back of a shelf or the space beneath a home''s floorboards. It wanders in search of prey after sunset.'),
  ('galar', 336, 10345, false, '앤티크한 찻주전자에 산다. 대부분 위작이지만 매우 드물게 진품이 발견되기도 한다.', 'This species lives in antique teapots. Most pots are forgeries, but on rare occasions, an authentic work is found.'),
  ('paldea', 238, 10345, false, '남겨진 홍차를 발견하면 자신의 몸을 흘러 들어가게 한다. 그 홍차는 포트데스가 된다.', 'Leaving leftover black tea unattended is asking for this Pokémon to come along and pour itself into it, turning the tea into a new Polteageist.'),
  ('paldea', 444, 10448, false, null, 'It pretends to be tea, trying to fool people into drinking it so it can drain their life-force. Its ruse is generally unsuccessful.')
on conflict (dex, species_id) do update set
  number = excluded.number,
  is_default = excluded.is_default,
  ko_description = excluded.ko_description,
  en_description = excluded.en_description;
