-- Generated by apps/pokedex-web/scripts/generate.ts from PokéAPI. Do not edit;
-- change the script and run it again.
--
-- Data from PokéAPI, © 2013–2023 Paul Hallett and PokéAPI contributors, BSD 3-Clause.
-- The licence is in LICENSES/PokeAPI-BSD-3-Clause.txt.
--
-- With the earlier generated migrations, it says every form up to national
-- No.1025 that its games had, 1485 of them, and their entries in the
-- national, kanto, johto, hoenn, sinnoh, unova, kalos, alola, galar, hisui, paldea, lumiose pokedexes. Only the rows that differ from what
-- those wrote are here, and the forms they wrote that are no longer in.

insert into public.pokedex_items (id, ko_name, en_name, sprite) values
  ('shiny-charm', '빛나는부적', 'Shiny Charm', '/sprites/items/shiny-charm.png')
on conflict (id) do update set
  ko_name = excluded.ko_name,
  en_name = excluded.en_name,
  sprite = excluded.sprite;
