-- Generated by apps/pokedex-web/scripts/generate.ts from PokéAPI. Do not edit;
-- change the script and run it again.
--
-- Data from PokéAPI, © 2013–2023 Paul Hallett and PokéAPI contributors, BSD 3-Clause.
-- The licence is in LICENSES/PokeAPI-BSD-3-Clause.txt.
--
-- With the earlier generated migrations, it says every form up to national
-- No.1025 that its games had, 1442 of them, and their entries in the
-- national, kanto, johto, hoenn, sinnoh, unova, kalos, alola, galar, hisui, paldea pokedexes. Only the rows that differ from what
-- those wrote are here, and the forms they wrote that are no longer in.

delete from public.pokedex_entries where species_id in (10065, 10219);
delete from public.pokedex_species where id in (10065, 10219);
