-- Generated by apps/pokedex-web/scripts/generate.ts from PokéAPI. Do not edit;
-- change the script and run it again.
--
-- Data from PokéAPI, © 2013–2023 Paul Hallett and PokéAPI contributors, BSD 3-Clause.
-- The licence is in LICENSES/PokeAPI-BSD-3-Clause.txt.
--
-- With the earlier generated migrations, it says every form up to national
-- No.809 that its games had, 1058 of them, and their entries in the
-- national, kanto, johto, hoenn, sinnoh, unova, kalos, alola pokedexes. Only the rows that differ from what
-- those wrote are here.

insert into public.pokedex_items (id, ko_name, en_name, sprite) values
  ('damp-rock', '축축한바위', 'Damp Rock', '/sprites/items/damp-rock.png'),
  ('linking-cord', '연결의끈', 'Linking Cord', '/drawn/items/linking-cord.png'),
  ('meltan-candy', '멜탄의사탕', 'Meltan Candy', '/drawn/items/meltan-candy.png'),
  ('prism-scale', '고운비늘', 'Prism Scale', '/sprites/items/prism-scale.png')
on conflict (id) do update set
  ko_name = excluded.ko_name,
  en_name = excluded.en_name,
  sprite = excluded.sprite;

insert into public.pokedex_moves (id, ko_name, en_name, type) values
  ('ancient-power', '원시의힘', 'Ancient Power', 'rock'),
  ('double-hit', '더블어택', 'Double Hit', 'normal'),
  ('dragon-ascent', '화룡점정', 'Dragon Ascent', 'flying'),
  ('dragon-pulse', '용의파동', 'Dragon Pulse', 'dragon'),
  ('mimic', '흉내내기', 'Mimic', 'normal'),
  ('rollout', '구르기', 'Rollout', 'rock'),
  ('stomp', '짓밟기', 'Stomp', 'normal')
on conflict (id) do update set
  ko_name = excluded.ko_name,
  en_name = excluded.en_name,
  type = excluded.type;
