-- Generated by apps/pokedex-web/scripts/generate.ts from PokéAPI. Do not edit;
-- change the script and run it again.
--
-- Data from PokéAPI, © 2013–2023 Paul Hallett and PokéAPI contributors, BSD 3-Clause.
-- The licence is in LICENSES/PokeAPI-BSD-3-Clause.txt.
--
-- With the earlier generated migrations, it says every form up to national
-- No.1025 that its games had, 1483 of them, and their entries in the
-- national, kanto, johto, hoenn, sinnoh, unova, kalos, alola, galar, hisui, paldea, lumiose pokedexes. Only the rows that differ from what
-- those wrote are here, and the forms they wrote that are no longer in.

insert into public.pokedex_evolution_methods (id, trigger, level, item, held_item, min_happiness, time_of_day, relative_physical_stats, min_beauty, chance, gender, known_move, location, party_species_id, trade_species_id, party_type, known_move_type, min_affection, needs_overworld_rain, turn_upside_down, region, version, natures, min_damage_taken, used_move, min_move_count, min_steps, needs_multiplayer) values
  ('level-up-happiness-160-knowing-fairy-move', 'level-up', null, null, null, 160, null, null, null, null, null, null, null, null, null, null, 'fairy', null, false, false, null, null, null, null, null, null, null, false),
  ('trade-holding-prism-scale', 'trade', null, null, 'prism-scale', null, null, null, null, null, null, null, null, null, null, null, null, null, false, false, null, null, null, null, null, null, null, false),
  ('use-item-scroll-of-darkness', 'use-item', null, 'scroll-of-darkness', null, null, null, null, null, null, null, null, null, null, null, null, null, null, false, false, null, null, null, null, null, null, null, false),
  ('use-item-scroll-of-waters', 'use-item', null, 'scroll-of-waters', null, null, null, null, null, null, null, null, null, null, null, null, null, null, false, false, null, null, null, null, null, null, null, false),
  ('use-move-using-barb-barrage-20-times', 'use-move', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, false, false, null, null, null, null, 'barb-barrage', 20, null, false)
on conflict (id) do update set
  trigger = excluded.trigger,
  level = excluded.level,
  item = excluded.item,
  held_item = excluded.held_item,
  min_happiness = excluded.min_happiness,
  time_of_day = excluded.time_of_day,
  relative_physical_stats = excluded.relative_physical_stats,
  min_beauty = excluded.min_beauty,
  chance = excluded.chance,
  gender = excluded.gender,
  known_move = excluded.known_move,
  location = excluded.location,
  party_species_id = excluded.party_species_id,
  trade_species_id = excluded.trade_species_id,
  party_type = excluded.party_type,
  known_move_type = excluded.known_move_type,
  min_affection = excluded.min_affection,
  needs_overworld_rain = excluded.needs_overworld_rain,
  turn_upside_down = excluded.turn_upside_down,
  region = excluded.region,
  version = excluded.version,
  natures = excluded.natures,
  min_damage_taken = excluded.min_damage_taken,
  used_move = excluded.used_move,
  min_move_count = excluded.min_move_count,
  min_steps = excluded.min_steps,
  needs_multiplayer = excluded.needs_multiplayer;

insert into public.pokedex_latest_evolutions (species_id, evolution_method) values
  (350, 'trade-holding-prism-scale'),
  (462, 'use-item-thunder-stone'),
  (470, 'use-item-leaf-stone'),
  (471, 'use-item-ice-stone'),
  (476, 'use-item-thunder-stone'),
  (700, 'level-up-happiness-160-knowing-fairy-move'),
  (738, 'use-item-thunder-stone'),
  (740, 'use-item-ice-stone'),
  (892, 'use-item-scroll-of-darkness'),
  (10360, 'use-item-scroll-of-waters'),
  (904, 'use-move-using-barb-barrage-20-times')
on conflict (species_id) do update set
  evolution_method = excluded.evolution_method;
